title = "Leetcode 之旅"
languageCode = "zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

baseURL = "https://zrcoder.github.io/leetcode"

theme = "hugo-book"


enableGitInfo = true

[params]
  BookTheme = "light"
  BookToC = false
  BookSection = "docs"
  BookRepo = "https://github.com/zrcoder/leetcode"
  BookCommitPath = "commit"
  BookEditPath = "edit/hugo-book"
  BookComments = true
  BookDateFormat = "2006年1月2日"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'rainbow_dash'
    tabWidth = 4
