title = "Leetcode 之旅"
languageCode = "zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

baseURL = "https://rdcode.netlify.app/"

theme = "hugo-book"


enableGitInfo = true
disqusShortname = "rdcode"

[params]
  BookTheme = "light"
  BookToC = true
  BookSection = "docs"
  BookRepo = "https://github.com/zrcoder/leetcode"
  BookCommitPath = "commit"
  BookEditPath = "edit/hugo-book"
  BookComments = false
  BookDateFormat = "2006年1月2日"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'manni'
    # style = 'Tango'
    # style = "monokailight"
    tabWidth = 4
